为了便于使用诸如IPython之类的python交互环境，可以使用InteractiveSession代替Session类，使用Tensor.eval()和Operation.run()方法代替Session.run()。这样可以避免使用一个变量来持有会话：

In [1]:
# 进入一个交互式Tensorflow会话
import tensorflow as tf

In [5]:
sess = tf.InteractiveSession()

x=tf.Variable([1.0,2.0])
a=tf.constant([3.0,3.0])

# 使用初始化器initializer op的run()方法初始化x
x.initializer.run()

# 增加一个减法sub op，从x减去a。运行减法op，输出结果
div = tf.divide(x,a)
sub = tf.subtract(x,a)

In [6]:
sess.run(sub)

array([-2., -1.], dtype=float32)

In [7]:
sess.run(div)

array([ 0.33333334,  0.66666669], dtype=float32)

In [8]:
x.eval()

array([ 1.,  2.], dtype=float32)

In [9]:
a.eval()

array([ 3.,  3.], dtype=float32)

In [10]:
sess.close()