In [1]:
import tensorflow as tf

In [11]:
sess = tf.InteractiveSession()

In [12]:
a=tf.constant([1, 2, 3, 4, 5, 6, 7]) 
b=tf.constant([1, 1, 2, 4, 5, 6, 7]) 

In [13]:
compare = tf.greater(a,b)

In [14]:
result = sess.run(compare)

In [15]:
result

array([False,  True,  True, False, False, False, False], dtype=bool)

In [16]:
toint = tf.cast(result, tf.int64)
tofloat = tf.cast(result, tf.float32)

In [18]:
sess.run(toint)

array([0, 1, 1, 0, 0, 0, 0], dtype=int64)

In [19]:
sess.run(tofloat)

array([ 0.,  1.,  1.,  0.,  0.,  0.,  0.], dtype=float32)